env:
  - INTRAVENOUS=yes

os:
  - linux

branches:
  only:
    - master

language: node_js
node_js:
  - "11"
  - "10"
  - "8"

#script: "npm run-script test"
script: "npm run-script test-cover"
after_success: "npm run report-coverage"
after_failure: "cat /home/travis/build/happner/happner/npm-debug.log"
